import './globals.css'
import type { Metadata } from 'next'

import { ThemeProvider } from '@/components/theme-provider'
import { poppins } from '@/lib/localFonts'
import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={poppins.className}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system">
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
