import './globals.css'
import type { Metadata } from 'next'

import { ThemeProvider } from '@/components/theme-provider'
import {
  //  caveat,
  poppins
} from '@/lib/localFonts'
import Header from '@/components/header'
import ReturnToHeader from '@/components/return-to-header'
import { Toaster } from '@/components/ui/toaster'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.variable}`}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="dark">
          <Header />

          {children}

          <ReturnToHeader />

          <Toaster />

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
